import type { Metadata } from "next"
import { FC, ReactNode } from "react"
import { Providers } from "app/providers"

type Props = {
  children: ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout: FC<Props> = (props) => {
  return (
    <html>
      <body>
        <Providers>{props.children}</Providers>
      </body>
    </html>
  )
}
export default RootLayout
